#!/bin/env bash

#picom --experimental-backend &
pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
numlockx on &
nm-applet &
feh --bg-scale "$HOME/.config/pictures/6.jpg"
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
$HOME/.config/polybar/launch.sh &

$HOME/.config/.touchpad.sh
