;; ┌────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▄░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█▀▄░█▀█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀░░▀░▀░▀░▀░▀▀▀│
;; │░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░│
;; └────────────────────────────────────────────────────┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[bar]
fill = •
empty = ·
indicator = ⏽
; Nerd font :   ,  ⏽,  樂 籠 錄 , 雷 絛 ,  , 

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/volume]
type = internal/alsa
master-soundcard = default
speaker-soundcard = default
headphone-soundcard = default

master-mixer = Master
interval = 5
format-volume = <ramp-volume> <bar-volume>
format-muted-prefix = 
label-volume = %percentage%%
label-muted = " Muted"
label-muted-foreground = ${color.red}

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

bar-volume-width = 10
bar-volume-gradient = false

bar-volume-indicator = ${bar.indicator}
bar-volume-indicator-foreground = ${color.foreground}

bar-volume-fill = ${bar.fill}
bar-volume-foreground-0 = ${color.green}
bar-volume-foreground-1 = ${color.green}
bar-volume-foreground-2 = ${color.yellow}
bar-volume-foreground-3 = ${color.yellow}
bar-volume-foreground-4 = ${color.red}

bar-volume-empty = ${bar.empty}
bar-volume-empty-foreground = ${color.foreground}

ramp-headphones-0 = 

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/brightness]
type = internal/backlight

card = intel_backlight
format = <bar>
format-prefix = "盛 "
label = %percentage%%

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
ramp-4 = 

bar-width = 10
bar-gradient = false

bar-indicator = ${bar.indicator}
bar-indicator-foreground = ${color.foreground}

bar-fill = ${bar.fill}
bar-foreground-0 = ${color.green}
bar-foreground-1 = ${color.green}
bar-foreground-2 = ${color.yellow}
bar-foreground-3 = ${color.yellow}
bar-foreground-4 = ${color.red}

bar-empty = ${bar.empty}
bar-empty-foreground = ${color.foreground}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/battery_bar]
type = custom/script
exec = ~/.config/polybar/scripts/battery
interval = 5
format = <label>
label = %output%
click-left = xfce4-power-manager-settings &

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/cpu_bar]
type = internal/cpu
interval = 0.5

format = <bar-load> <label>
format-prefix = "﬙ "

label = "%percentage%%"

bar-load-width = 10
bar-load-gradient = false

bar-load-indicator = ${bar.indicator}
bar-load-indicator-foreground = ${color.foreground}

bar-load-fill = ${bar.fill}
bar-load-foreground-0 = ${color.green}
bar-load-foreground-1 = ${color.green}
bar-load-foreground-2 = ${color.yellow}
bar-load-foreground-3 = ${color.yellow}
bar-load-foreground-4 = ${color.red}

bar-load-empty = ${bar.empty}
bar-load-empty-foreground = ${color.foreground}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/filesystem_bar]
type = internal/fs
mount-0 = /
interval = 30

fixed-values = false

format-mounted = <bar-used> <label-mounted>
format-mounted-prefix = " "

format-unmounted = <label-unmounted>
format-unmounted-prefix = " "

label-mounted = %used%/%total%
label-unmounted = %mountpoint%: not mounted

bar-used-width = 10
bar-used-gradient = false

bar-used-indicator = ${bar.indicator}
bar-used-indicator-foreground = ${color.foreground}

bar-used-fill = ${bar.fill}
bar-used-foreground-0 = ${color.green}
bar-used-foreground-1 = ${color.green}
bar-used-foreground-2 = ${color.yellow}
bar-used-foreground-3 = ${color.yellow}
bar-used-foreground-4 = ${color.red}

bar-used-empty = ${bar.empty}
bar-used-empty-foreground = ${color.foreground}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/memory_bar]
type = internal/memory
interval = 2

format = <bar-used> <label>
format-prefix = " "

label = "%mb_used%"

bar-used-width = 10
bar-used-gradient = false

bar-used-indicator = ${bar.indicator}
bar-used-indicator-foreground = ${color.foreground}

bar-used-fill = ${bar.fill}
bar-used-foreground-0 = ${color.green}
bar-used-foreground-1 = ${color.green}
bar-used-foreground-2 = ${color.yellow}
bar-used-foreground-3 = ${color.yellow}
bar-used-foreground-4 = ${color.red}

bar-used-empty = ${bar.empty}
bar-used-empty-foreground = ${color.foreground}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/mpd_bar]
type = internal/mpd
interval = 1
format-online = <label-song> <bar-progress> <label-time>
format-online-prefix = ﱘ 
format-offline = <label-offline>
format-offline-prefix = ﱘ

label-song =  " %artist% - %title%"
label-song-maxlen = 25
label-song-ellipsis = true
label-time = %elapsed% / %total%
label-offline = " Offline"

icon-play = 
icon-pause = 
icon-stop = 
icon-prev = 
icon-next = 
icon-seekb = 
icon-seekf = 
icon-random = 
icon-repeat = 
icon-repeatone = 
icon-single = 
icon-consume = 

toggle-on-foreground = ${color.primary}
toggle-off-foreground = ${color.red}

bar-progress-width = 10
bar-progress-gradient = false

bar-progress-indicator = ${bar.indicator}
bar-progress-indicator-foreground = ${color.yellow}

bar-progress-fill = ${bar.fill}
bar-progress-foreground-0 = ${color.yellow}

bar-progress-empty = ${bar.empty}
bar-progress-empty-foreground = ${color.foreground}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
